# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
           
jobs:
  generate-snake:
    runs-on: ubuntu-latest
    
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
            github_user_name: ${{ github.repository_owner }}
            outputs: |
                assets/decoration_generate_snake.svg
                assets/decoration_generate_snake_dark.svg?palette=github-dark
                assets/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
            GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
    
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: ./*.svg
          message: 'Update Decoration: Generate Snake'
          default_author: github_actions
