# This is a basic workflow to help you get started with Actions

name: Random Script

on:
  schedule:
    - cron: '0 11 * * *'  # 每天中午12点执行
  workflow_dispatch:

jobs:
  random-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: run script
        run: ./script/random_script.sh 2

